In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')


In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset.drop('NObeyesdad',axis=1,inplace=True)

In [5]:
my_object_df = dataset.select_dtypes(include='object')
my_object_df.head()

Gender family_history_with_overweight FAVC       CAEC SMOKE  SCC  \
0  Female                            yes   no  Sometimes    no   no   
1  Female                            yes   no  Sometimes   yes  yes   
2    Male                            yes   no  Sometimes    no   no   
3    Male                             no   no  Sometimes    no   no   
4    Male                             no   no  Sometimes    no   no   

         CALC                 MTRANS  
0          no  Public_Transportation  
1   Sometimes  Public_Transportation  
2  Frequently  Public_Transportation  
3  Frequently                Walking  
4   Sometimes  Public_Transportation

In [6]:
my_numeric_df = dataset.select_dtypes(exclude='object')
my_numeric_df.head()

Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE
0  21.0    1.62    64.0   2.0  3.0   2.0  0.0  1.0
1  21.0    1.52    56.0   3.0  3.0   3.0  3.0  0.0
2  23.0    1.80    77.0   2.0  3.0   2.0  2.0  1.0
3  27.0    1.80    87.0   3.0  3.0   2.0  2.0  0.0
4  22.0    1.78    89.8   2.0  1.0   2.0  0.0  0.0

In [7]:
dummy_df = pd.get_dummies(my_object_df,drop_first=True)

In [8]:
final_df = pd.concat([my_numeric_df,dummy_df],axis=1)
final_df.head()

Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE  Gender_Male  \
0  21.0    1.62    64.0   2.0  3.0   2.0  0.0  1.0            0   
1  21.0    1.52    56.0   3.0  3.0   3.0  3.0  0.0            0   
2  23.0    1.80    77.0   2.0  3.0   2.0  2.0  1.0            1   
3  27.0    1.80    87.0   3.0  3.0   2.0  2.0  0.0            1   
4  22.0    1.78    89.8   2.0  1.0   2.0  0.0  0.0            1   

   family_history_with_overweight_yes  ...  CAEC_no  SMOKE_yes  SCC_yes  \
0                                   1  ...        0          0        0   
1                                   1  ...        0          1        1   
2                                   1  ...        0          0        0   
3                                   0  ...        0          0        0   
4                                   0  ...        0          0        0   

   CALC_Frequently  CALC_Sometimes  CALC_no  MTRANS_Bike  MTRANS_Motorbike  \
0                0               0        1            0                 0   
1                0               1        0            0                 0   
2                1               0        0            0                 0   
3                1               0        0            0                 0   
4                0               1        0            0                 0   

   MTRANS_Public_Transportation  MTRANS_Walking  
0                             1               0  
1                             1               0  
2                             1               0  
3                             0               1  
4                             1               0  

[5 rows x 23 columns]

In [9]:
X= final_df.iloc[:, :].values
print(X)

[[ 21.         1.62      64.       ...   0.         1.         0.      ]
 [ 21.         1.52      56.       ...   0.         1.         0.      ]
 [ 23.         1.8       77.       ...   0.         1.         0.      ]
 ...
 [ 22.524036   1.752206 133.689352 ...   0.         1.         0.      ]
 [ 24.361936   1.73945  133.346641 ...   0.         1.         0.      ]
 [ 23.664709   1.738836 133.472641 ...   0.         1.         0.      ]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 1 1 ... 4 4 4]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[74  4  0  0  0  0  0]
 [ 4 62  0  0  0  2  1]
 [ 0  0 84  2  0  0  0]
 [ 0  0  2 71  0  0  0]
 [ 0  0  0  0 88  0  0]
 [ 0  5  0  0  0 61  2]
 [ 0  0  2  0  0  5 59]]


0.9450757575757576