# Kernel SVM

## Importing the libraries

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [20]:
dataset = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [21]:
dataset.drop('NObeyesdad',axis=1,inplace=True)

In [22]:
my_object_df= dataset.select_dtypes(include='object')
my_numeric_df= dataset.select_dtypes(exclude='object')
dummy_df = pd.get_dummies(my_object_df,drop_first=True)
final_df= pd.concat([my_numeric_df,dummy_df],axis=1)
X= final_df.iloc[:, :].values

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(X)


[1 1 1 ... 4 4 4]
[[ 21.         1.62      64.       ...   0.         1.         0.      ]
 [ 21.         1.52      56.       ...   0.         1.         0.      ]
 [ 23.         1.8       77.       ...   0.         1.         0.      ]
 ...
 [ 22.524036   1.752206 133.689352 ...   0.         1.         0.      ]
 [ 24.361936   1.73945  133.346641 ...   0.         1.         0.      ]
 [ 23.664709   1.738836 133.472641 ...   0.         1.         0.      ]]


In [ ]:
print(y)

## Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:8] = sc.fit_transform(X_train[:,:8])
X_test[:,:8] = sc.transform(X_test[:,:8])

## Training the Kernel SVM model on the Training set

In [26]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[74  4  0  0  0  0  0]
 [ 2 59  0  0  0  7  1]
 [ 0  0 83  1  0  0  2]
 [ 0  0  0 73  0  0  0]
 [ 0  0  0  0 88  0  0]
 [ 0  4  1  0  0 59  4]
 [ 0  3  3  0  0  4 56]]


0.9318181818181818