# Naive Bayes

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset.drop('NObeyesdad',axis=1,inplace=True)

In [4]:
my_object_df= dataset.select_dtypes(include='object')
my_numeric_df= dataset.select_dtypes(exclude='object')
dummy_df = pd.get_dummies(my_object_df,drop_first=True)
final_df= pd.concat([my_numeric_df,dummy_df],axis=1)
X= final_df.iloc[:, :].values

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(X)


[[ 21.         1.62      64.       ...   0.         1.         0.      ]
 [ 21.         1.52      56.       ...   0.         1.         0.      ]
 [ 23.         1.8       77.       ...   0.         1.         0.      ]
 ...
 [ 22.524036   1.752206 133.689352 ...   0.         1.         0.      ]
 [ 24.361936   1.73945  133.346641 ...   0.         1.         0.      ]
 [ 23.664709   1.738836 133.472641 ...   0.         1.         0.      ]]


In [6]:
print(y)

[1 1 1 ... 4 4 4]


## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:8] = sc.fit_transform(X_train[:,:8])
X_test[:,:8] = sc.transform(X_test[:,:8])

## Training the Naive Bayes model on the Training set

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Making the Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[76  1  0  0  0  1  0]
 [55  6  1  0  0  5  2]
 [ 3  2 59 18  1  0  3]
 [ 0  0 12 60  0  0  1]
 [ 0  0  1  0 87  0  0]
 [26  6 21  1  0 11  3]
 [15  3 29 12  0  1  6]]


0.5776515151515151